import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Global language notifier — any widget can read or toggle the locale.
final ValueNotifier<Locale> localeNotifier = ValueNotifier(const Locale('en'));

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)
        ?? AppLocalizations(const Locale('en'));
  }

  bool get isArabic => locale.languageCode == 'ar';

  static Future<void> setLocale(String langCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', langCode);
    localeNotifier.value = Locale(langCode);
  }

  static Future<void> loadSavedLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final code = prefs.getString('app_language') ?? 'en';
    localeNotifier.value = Locale(code);
  }

  String get(String key) => _strings[locale.languageCode]?[key] ?? _strings['en']![key] ?? key;

  /// Translates a raw order status value (e.g. 'in_transit') to a
  /// human-readable, localized label. Falls back to the raw value if unknown.
  String statusLabel(String status) {
    const map = {
      'pending_admin'     : 'pending_admin',
      'pending'           : 'pending',
      'assigned'          : 'assigned',
      'accepted'          : 'accepted',
      'in_transit'        : 'in_transit',
      'rejected'          : 'rejected',
      'completed'         : 'completed_status',
      'waitlist'          : 'waitlist',
      'expired'           : 'expired',
      'delivery_rejected' : 'delivery_rejected',
    };
    final key = map[status];
    if (key == null) return status;
    return get(key);
  }

  static const Map<String, Map<String, String>> _strings = {
    'en': {
      // General
      'app_name': 'OilTrade',
      'ok': 'OK',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'sign_out': 'Sign Out',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'retry': 'Retry',
      'submit': 'Submit',
      'back': 'Back',

      // Auth
      'email': 'Email',
      'password': 'Password',
      'phone': 'Phone',
      'name': 'Full Name',
      'wilaya': 'Wilaya',
      'role': 'Role',
      'seller': 'Seller',
      'buyer': 'Buyer',
      'delivery': 'Delivery Agent',
      'create_account': 'Create Account',
      'select_role': 'Select your role',
      'seller_type': 'Seller Type',
      'house': 'House',
      'house_desc': 'Individual household',
      'business': 'Business',
      'business_desc': 'Restaurant, hotel, café…',
      'strength_weak': 'Weak',
      'strength_fair': 'Fair',
      'strength_good': 'Good',
      'strength_strong': 'Strong',
      'sign_in_subtitle': 'Sign in to your account',
      'forgot_password': 'Forgot password?',
      'no_account': "Don't have an account? ",
      'email_not_verified': 'Email Not Verified',
      'resend_otp_dialog': 'Your email is not verified. We will resend the OTP code to your email.',
      'send_otp': 'Send OTP',
      'verify_email': 'Verify Email',
      'check_email': 'Check your email',
      'otp_sent_to': 'We sent a 6-digit code to',
      'verify': 'Verify',
      'resend_in': 'Resend in',
      'resend_otp': 'Resend OTP',
      'enter_all_digits': 'Please enter all 6 digits',
      'invalid_otp': 'Invalid or expired OTP',
      'reset_password': 'Reset Password',
      'reset_password_subtitle': "Enter your email address and we'll send you a 6-digit code to reset your password.",
      'send_reset_code': 'Send Reset Code',
      'enter_reset_code': 'Enter reset code',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'set_new_password': 'Set new password',
      'code_verified_subtitle': 'Code verified. Choose a strong password\nof at least 8 characters.',
      'password_mismatch': 'Passwords do not match',
      'password_min': 'Password must be at least 8 characters',
      'resend_code': 'Resend Code',
      'verify_code': 'Verify Code',
      'code_resent': 'Code resent. Check your email.',
      'otp_resent': 'OTP resent successfully. Check your email.',
      'password_reset_success': 'Password reset successfully. You can now log in.',

      // Profile
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'contact_info': 'Contact Info',
      'activity_stats': 'Activity Stats',
      'notifications': 'Notifications',
      'order_updates_enabled': 'Order updates enabled',
      'notifications_off': 'Notifications off',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'choose_language': 'Choose Language',
      'privacy_security': 'Privacy & Security',
      'help_support': 'Help & Support',
      'share_app': 'Share App',
      'about': 'About OilTrade',
      'report_problem': 'Report a Problem 🚨',
      'report_subtitle': 'Open a support ticket and our team will respond within hours',
      'availability': 'Availability',
      'accepting_orders': 'Accepting orders',
      'not_accepting_orders': 'Not accepting orders',
      'capacity': 'Capacity',
      'ccp': 'CCP',
      'not_set': 'Not set',
      'collections': 'Collections',
      'orders': 'Orders',
      'rating': 'Rating',
      'completed': 'Completed',
      'profile_updated': 'Profile updated successfully!',
      'update_failed': 'Update failed',
      'sign_out_confirm': 'Sign out?',
      'sign_out_confirm_body': 'Are you sure you want to sign out?',
      'phone_number': 'Phone Number',
      'max_capacity': 'Max Capacity (litres per trip)',
      'min_3_chars': 'Minimum 3 characters',
      'valid_phone': 'Enter a valid phone number',
      'required': 'Required',
      'valid_number': 'Enter a valid number ≥ 1',

      // Help items
      'help_q1': 'How does the app work?',
      'help_a1': 'OilTrade gather three parties: the seller (collects used oil), the buyer (purchases it), and the delivery agent who transports it. Each role has a dedicated interface with its own permissions.',
      'help_q2': 'How do I request a collection for my used oil?',
      'help_a2': 'From the home screen, tap "Request Collection", enter the quantity, address, and pickup date, then submit the request. An available delivery agent will be assigned automatically.',
      'help_q3': 'How do I buy oil as a buyer?',
      'help_a3': 'Create a purchase order specifying the quantity, delivery address, and date. The price is calculated automatically.',
      'help_q4': 'Who gets rated in the app?',
      'help_a4': 'Only the delivery agent is rated — by the seller after collection and by the buyer after delivery. Ratings are from 1 to 5 stars.',
      'help_q5': 'What payment method is accepted?',
      'help_a5': 'Payment is made via postal transfer (CCP) or BaridiMob. After the transfer, upload a photo of the receipt in the app.',
      'help_q6': 'What do I do if I encounter a problem?',
      'help_a6': 'Go to your Profile and tap "Report a Problem" to open a support ticket.',
      'common_questions': 'Common questions about using the app',

      // About
      'about_tagline': "Algeria's first platform for used cooking oil trading.",
      'copyright': '© 2026 OilTrade . All rights reserved.',
      'version': 'Version 1.0.0',
      'algeria': 'Algeria',

      // Home - Seller
      'hello': 'Hello',
      'request_collection': 'Request Collection',
      'request_collection_subtitle': 'Schedule a pickup for your used oil',
      'collection_history': 'Collection History',
      'recent_collections': 'Recent Collections',
      'recent_orders': 'Recent Orders',
      'no_orders_yet': 'No orders yet',
      'no_collections_yet': 'No collections yet',
      'view_all': 'View All',
      'total_earned': 'Total Earned',
      'total_sold': 'Total Sold',
      'home': 'Home',
      'history': 'History',
      'products': 'Products',
      'status': 'Status',
      'liters': 'liters',
      'liter_unit': 'L',
      'order_hash': 'Order #',
      'collection_hash': 'Collection #',
      'purchase_hash': 'Purchase #',
      'quota': 'Quota',
      'l_per_month': 'L/mo',
      'l_per_trip': 'L / trip',

      // Home - Buyer
      'place_order': 'Place Order',
      'place_an_order': 'Place an Order',
      'place_order_subtitle': 'Order cooking oil, delivered to you',
      'my_orders': 'My Orders',
      'subscription': 'Subscription',
      'subscription_pending': 'Subscription Pending',
      'subscription_pending_subtitle': 'plan is awaiting admin approval',
      'subscribe_to_plan': 'Subscribe to a Plan',
      'subscribe_to_plan_subtitle': 'Choose Basic, Premium, or VIP to start ordering',
      'upgrade_plan': 'Upgrade plan →',
      'active': 'Active',
      'pending': 'Pending',
      'no_active_subscription': 'No active subscription',
      'subscribe': 'Subscribe',

      // Order statuses
      'pending_admin': 'Pending Approval',
      'assigned': 'Assigned',
      'accepted': 'Accepted',
      'in_transit': 'In Transit',
      'rejected': 'Rejected',
      'completed_status': 'Completed',
      'waitlist': 'Waitlist',
      'expired': 'Expired',
      'delivery_rejected': 'Rejected by Driver',

      // Collection request
      'new_collection': 'New Collection Request',
      'quantity_liters': 'Quantity (litres)',
      'pickup_address': 'Pickup Address',
      'pickup_date': 'Pickup Date',
      'pickup_time': 'Pickup Time (optional)',
      'notes': 'Notes (optional)',
      'quality': 'Quality',
      'good_quality': 'Good Quality',
      'medium': 'Medium',
      'submit_request': 'Submit Request',
      'select_date': 'Select Date',
      'select_time': 'Select Time',
      'estimated_earnings': 'Estimated earnings',

      // FAQ screen
      'faq_title': 'FAQ',
      'faq_header': 'Everything you need to know about used oil',
      'faq_tap_to_read': 'Tap any question to read the answer',
      'faq_q1': 'What is OilTrade?',
      'faq_a1': "OilTrade is Algeria's first platform dedicated to used cooking oil trading, acting as an intermediary between used cooking oil collectors, buyers, and delivery agents.",
      'faq_q2': 'Why should used oil not be poured down the drain?',
      'faq_a2': "Just one litre of used cooking oil can contaminate one million litres of groundwater. Pouring it down the drain clogs pipes, damages sewage networks, and harms aquatic life. OilTrade gives you a responsible alternative: sell your oil instead of dumping it.",
      'faq_q3': 'What types of oil are accepted on the platform?',
      'faq_a3': "We accept all used household and commercial cooking oils, including:\n\n• Sunflower oil\n\nThe only requirement: the oil must be free of excessive food residue. We do not accept engine oils or petroleum derivatives.",
      'faq_q4': 'What is the minimum quantity for a collection request?',
      'faq_a4': "The minimum per request is fifteen litres (15 L). There is no upper limit — the more you collect, the more you earn.",
      'faq_q5': 'How is the oil collection price calculated?',
      'faq_a5': "The used oil collection price is fixed. Once you accumulate 15 litres, you receive a reward.\n\nThe progress tracker inside the app shows how many litres you have collected and when you will reach the minimum payout threshold.",
      'faq_q6': 'How does the collection process work?',
      'faq_a6': "1. Submit a collection request in the app, specifying the quantity, address, and pickup date.\n2. A delivery agent from your wilaya is automatically assigned.\n3. The agent arrives at the scheduled time to pick up the oil.\n4. Your litre balance is updated as soon as the pickup is completed.\n5. You can rate the delivery agent after the pickup.",
      'faq_q7': 'How should I store used oil before collection?',
      'faq_a7': "Follow these simple guidelines:\n\n• Let it cool completely before storing\n• Strain out large food particles\n• Pour it into a tightly sealed plastic or glass container\n• Store in a cool place away from direct sunlight\n• Avoid mixing it with water or other oils whenever possible",
      'faq_q8': 'What subscription plans are available for buyers?',
      'faq_a8': "Buyers can choose from three plans:\n\n• Basic: 100 L/month — 10,000 DZD (Priority 1)\n• Premium: 200 L/month — 20,000 DZD (Priority 2)\n• VIP: 300 L/month — 30,000 DZD (Priority 3)\n\nHigher-priority plans get preference in delivery scheduling.",
      'faq_q9': 'How does the rating system work?',
      'faq_a9': "After every collection or delivery, the delivery agent is rated by the seller or buyer independently. Ratings help improve service quality and identify the best delivery agents.",
      'faq_q10': 'What is the environmental impact of using OilTrade?',
      'faq_a10': "By trading used oil instead of dumping it:\n\n• You protect groundwater and rivers from pollution\n• You reduce carbon emissions compared to burning waste\n• You support the Circular Economy\n• You contribute to Algeria's sustainable development goals\n\nEvery litre you sell is a step towards a cleaner Algeria.",

      // Request collection
      'oil_quantity': 'Oil Quantity',
      'oil_photo': 'Oil Photo',
      'upload_oil_photo': 'Upload Oil Photo (optional)',
      'listing_submitted': 'Listing Submitted!',
      'listing_submitted_body': 'Your listing has been sent to the admin for review.\nYou will be notified once it is approved.',
      'status_pending_admin': 'Status: Pending Admin Approval',
      'back_to_home': 'Back to Home',
      'submit_listing': 'Submit Listing',
      'submitting': 'Submitting...',
      'take_photo': 'Take Photo',
      'choose_from_gallery': 'Choose from Gallery',
      'use_current_location': 'Use Current Location',
      'getting_location': 'Getting location...',

      // Subscription screen
      'choose_a_plan': 'Choose a Plan',
      'subscription_submitted': 'Subscription Submitted!',
      'subscription_submitted_body': 'Your payment receipt is under review. Your plan will be activated once confirmed.',
      'payment_ccp_title': 'Payment via CCP / Baridimob',
      'payment_ccp_body': 'Transfer the subscription fee to our CCP account, then upload your Baridimob receipt below.',
      'upload_baridimob_receipt': 'Upload Baridimob Receipt',
      'tap_to_select_gallery': 'Tap to select from gallery',
      'subscribe_now': 'Subscribe Now',
      'priority_score': 'Priority Score: ',
      'per_month': '/month',

      // Place order screen
      'place_oil_order': 'Place Oil Order',
      'payment': 'Payment',
      'added_to_waitlist': 'Added to Waitlist',
      'order_submitted': 'Order Submitted!',
      'waitlist_body': 'Your order is on the waitlist. It will be processed once enough stock is available.',
      'order_submitted_body': 'Your payment receipt has been submitted. Admin will verify and assign a delivery agent.',
      'status_waitlisted': 'Status: Waitlisted',
      'status_pending_verification': 'Status: Pending Verification',
      'pay_via_baridi': 'Pay via Baridi Mob / CCP',
      'pay_transfer_instruction': 'Transfer the exact amount to our CCP account below, then upload your Baridi Mob receipt.',
      'oiltrade_ccp_account': 'OilTrade CCP Account',
      'upload_payment_receipt': 'Upload Payment Receipt',
      'tap_to_upload_receipt': 'Tap to upload receipt (required)',
      'receipt_note': 'Please attach a screenshot or photo of your Baridi Mob payment confirmation.',
      'ive_paid_submit': "I've Paid — Submit Order",
      'back_to_order_details': '← Back to order details',
      'order_form_banner': 'Fill in your order details. If stock is available you will be asked to pay before confirming.',
      'required_quantity': 'Required Quantity',
      'oil_quality': 'Oil Quality',
      'delivery_date': 'Delivery Date',
      'delivery_location': 'Delivery Location',
      'place_order_btn': 'Place Order',
      'estimated_total': 'Estimated total',
      'amount_to_pay': 'Amount to pay',

      // Complaint
      'complaint_title': 'Report a Problem',
      'problem_type': 'Problem Type',
      'description': 'Description',
      'send': 'Send',
      'complaint_screen_title': 'Report a Problem 🚨',
      'complaint_support_title': 'Open a direct support ticket',
      'complaint_support_body': 'Our team will respond within hours directly to your email.',
      'complaint_type_label': 'Problem Type',
      'complaint_desc_label': 'Description',
      'complaint_desc_hint': 'Describe the problem in detail...',
      'complaint_submit': 'Submit Ticket',
      'complaint_submitted': '✅ Ticket submitted!',
      'complaint_submitted_body': 'Our support team will respond within 24 hours to your registered email address.',
      'complaint_new_ticket': 'Open a new ticket',
      'complaint_go_back': 'Go back',
      'complaint_select_type': 'Please select a problem type',
      'complaint_enter_desc': 'Please describe the problem',
      'complaint_type_1': 'Order not received',
      'complaint_type_2': 'Oil quality issue',
      'complaint_type_3': 'Problem with driver',
      'complaint_type_4': 'Payment issue',
      'complaint_type_5': 'Other',

      // Collection history screen
      'first_pickup_hint': 'Request your first pickup from the Home tab',
      'rate_delivery_agent': 'Rate Delivery Agent',
      'collection_service_question': 'How was the collection service?',
      'you_rated': 'You rated: ',
      'payment_received': 'Payment Received',
      'receipt_load_error': 'Could not load receipt',
      'tap_full_size': 'Tap to view full size',

      // Purchase orders screen
      'order_not_fulfilled_title': 'Order Could Not Be Fulfilled',
      'order_not_fulfilled_body': 'Your order was cancelled because the requested oil was not available by the delivery date.\n\nPlease place a new order.',
      'dismiss': 'Dismiss',
      'reorder': 'Re-order',
      'delivery_service_question': 'How was the delivery service?',
      'order_cancelled_status': 'Order Cancelled — Stock Unavailable',
      'order_waitlist_status': 'In Waitlist — Waiting for Stock',
      'order_cancelled_body': 'The oil stock was not available by your delivery date. Please place a new order.',
      'order_waitlist_body': 'Your order is queued and will be fulfilled when stock becomes available.',
      'deliver_prefix': 'Deliver: ',
      'ordered': 'ordered',
      'place_order_label': 'Place Order',

      // Delivery home screen
      'payments': 'Payments',
      'avg_rating': 'Avg Rating',
      'no_collection_tasks': 'No collection tasks assigned',
      'no_purchase_tasks': 'No purchase tasks assigned',
      'status_new': 'New',
      'accept_task': 'Accept Task',
      'purchases_tab': 'Purchases',
      'agent_badge': 'Agent',

      // Delivery payments screen
      'my_payments': 'My Payments',
      'total_received_prefix': 'Total received: ',
      'no_payments_yet': 'No payments yet',
      'paid_on_prefix': 'Paid on ',
      'payment_receipt_label': 'Payment Receipt',
      'receipt_unavailable': 'Receipt unavailable',
      'receipt': 'Receipt',
      'failed_to_load_image': 'Failed to load image',

      // Delivery order detail screen
      'reject_task': 'Reject Task',
      'reject_task_confirm': 'Are you sure you want to reject this task? It will be reassigned.',
      'reject': 'Reject',
      'confirm_delivery': 'Confirm Delivery',
      'confirm_delivery_body': 'Confirm that the delivery has been completed.',
      'started_pickup': 'Started Pickup',
      'started_delivery': 'Started Delivery',
      'delivery_completed': 'Delivery Completed',
      'task_completed': 'Task Completed',
      'pickup_location': 'Pickup Location',
      'central_depot_pickup': 'Central depot (pickup point)',
      'central_depot_dropoff': 'Central depot (drop-off point)',
      'information': 'Information',
      'schedule_details': 'SCHEDULE & DETAILS',
      'date_label': 'Date',
      'time_label': 'Time',
      'volume_label': 'Volume',
      'total_label': 'Total',
      'notes_label': 'Notes',
      'map': 'Map',
      'collection_task': 'Collection Task',
      'purchase_task': 'Purchase Task',
      'not_specified': 'Not specified',

      // Onboarding screen
      'onboarding_skip': 'Skip',
      'onboarding_next': 'Next',
      'onboarding_get_started': 'Get Started',
      'onboarding_slide1_title': 'Welcome to OilTrade',
      'onboarding_slide1_subtitle': 'Used Oil Platform',
      'onboarding_slide1_desc': "Algeria's first platform to act as an intermediary between used cooking oil collectors, buyers, and delivery agents — all in one app.",
      'onboarding_slide2_title': 'Sell Your Oil Easily',
      'onboarding_slide2_subtitle': 'For Sellers',
      'onboarding_slide2_desc': 'Register your used oil quantity, set a pickup date, and wait for a delivery agent.',
      'onboarding_slide3_title': 'Buy with Confidence',
      'onboarding_slide3_subtitle': 'For Buyers',
      'onboarding_slide3_desc': 'Subscribe to a plan, place your order, and get quality oil delivered right to your door.',

      // Oil progress widget
      'collection_progress': 'Collection Progress',
      'cycle_description': 'You collect oil in cycles of 15L. Once you reach 15L, the admin processes your collection and the cycle resets.',
      'cycle_progress': 'Cycle Progress',
      'to_complete': 'To Complete',
      'l_left': 'L left',
      'cycle_complete_banner': 'Cycle complete! The admin will process your collection and reset the cycle.',
      'collect_more_prefix': 'Collect ',
      'collect_more_suffix': 'L more to complete this cycle.',

      // Organic products screen
      'organic_products': 'Organic Products 🌿',
      'certified_products': '🌱 Certified Products — Available to All',
      'products_tap_hint': 'Tap a product to view details and contact the owner',
      'no_products': 'No products available',
      'list_product_cta': 'Want to list your product?',
      'list_product_body': 'Contact us to add your product on OilTrade and reach thousands of customers.',
      'product_description': 'Description',
      'owner_info': '📋 Owner Info',
      'contact_owner_hint': '💡 Contact the owner directly for inquiries or orders',

      // Subscription screen
      'plan_liters_month': '{liters}L/month',
      'val_upload_receipt': 'Please upload your Baridimob payment receipt',
      'subscription_failed': 'Subscription failed',
      'ccp_account_label': 'CCP Account:',
      'account_name_label': 'Name:',
      'plan_feature_basic_1': '100L/month quota',
      'plan_feature_basic_2': 'Standard delivery priority',
      'plan_feature_basic_3': 'Email support',
      'plan_feature_premium_1': '200L/month quota',
      'plan_feature_premium_2': 'High delivery priority',
      'plan_feature_premium_3': 'Priority support',
      'plan_feature_vip_1': '300L/month quota',
      'plan_feature_vip_2': 'Highest delivery priority',
      'plan_feature_vip_3': '24/7 dedicated support',

      // Notifications
      'collection_approved_title': 'Collection Order Approved',
      'purchase_approved_title': 'Purchase Order Approved',
      'collection_approved_body': 'Your collection order of {liters}L has been approved and a delivery agent will be assigned.',
      'purchase_approved_body': 'Your purchase order of {liters}L has been approved and a delivery agent has been assigned.',
      'collection_accepted_title': 'Delivery Agent On The Way',
      'collection_accepted_body': 'Your collection order of {liters}L has been accepted by the delivery agent.',
      'purchase_accepted_title': 'Delivery Agent Accepted',
      'purchase_accepted_body': 'Your purchase order of {liters}L has been accepted by the delivery agent.',
      'collection_rejected_title': 'Collection Order Rejected',
      'collection_rejected_body': 'Your collection request of {liters}L was rejected by the admin. Tap Reorder to try again.',
      'purchase_rejected_title': 'Purchase Order Rejected',
      'purchase_rejected_body': 'Your purchase order of {liters}L was rejected. Tap Reorder to try again.',
      'notif_action_reorder': 'Reorder',

      // Validators & hints (register screen)
      'val_name_min': 'Name must be at least 3 characters',
      'val_email': 'Enter a valid email',
      'val_password_required': 'Enter your password',
      'val_ccp_required': 'CCP account number is required',
      'val_capacity_required': 'Enter your vehicle capacity',
      'val_capacity_min': 'Enter a valid capacity (min 1L)',
      'hint_phone': '05XXXXXXXX',
      'hint_ccp': '0000000000/00',
      'hint_capacity': 'e.g. 20',
      'label_ccp_baridi': 'CCP / Baridi Mob Account Number',
      'label_vehicle_capacity': 'Vehicle Capacity (Liters)',

      // Auth errors
      'unknown_role': 'Unknown role. Please contact support.',
      'something_went_wrong': 'Something went wrong.',
      'password_reset_manual': 'Password reset. Please log in manually.',
      'failed_to_reset_password': 'Failed to reset password',
      'failed_to_resend_otp': 'Failed to resend OTP',

      // Request collection validators & info
      'label_quantity_min5': 'Quantity (Liters) — min 5 L',
      'val_enter_quantity': 'Enter quantity',
      'val_min_5_liters': 'Minimum 5 liters',
      'val_select_pickup_date': 'Please select a pickup date',
      'val_select_pickup_location': 'Please select a pickup location',
      'failed_to_submit': 'Failed to submit request',
      'label_address': 'Address',
      'val_enter_address': 'Enter pickup address',
      'orders_under_15l_info': 'Orders under 15L are collected at shared pickup points — twice a week.',
      'no_pickup_locations': 'No pickup locations available for your area. Contact support.',
      'listing_review_info': 'Your listing will be reviewed by our admin before being assigned to a delivery agent.',

      // Place order validators & snacks
      'location_disabled': 'Location service is disabled',
      'location_permission_denied': 'Location permission not granted',
      'location_error_prefix': 'Could not get location: ',
      'val_select_delivery_date': 'Please select a delivery date',
      'val_quantity_valid': 'Enter a valid quantity',
      'val_min_20l': 'Minimum order is 20 L',

      // Payment screen
      'order_confirmed': 'Order Confirmed!',
      'order_placed_prefix': 'Order #',
      'order_placed_suffix': ' has been placed successfully.',
      'order_details': 'Order Details',
      'order_id': 'Order ID',
      'quantity': 'Quantity',
      'total_amount': 'Total Amount',
      'address_label': 'Address',
      'payment_instructions': 'Payment Instructions',
      'payment_instructions_body': 'Transfer the total amount using one of the methods below, then show proof of payment to the delivery agent.',
      'ccp_cheque_postal': 'CCP (Chèque Postal)',
      'baridimob': 'BaridiMob',
      'done_go_to_orders': 'Done — Go to My Orders',
      'copied_to_clipboard': 'Copied to clipboard',

      // Delivery action toasts
      'toast_task_accepted': 'Task accepted!',
      'failed_to_accept_task': 'Failed to accept task',
      'toast_task_rejected': 'Task rejected.',
      'toast_pickup_started': 'Pickup started!',
      'toast_delivery_started': 'Delivery started!',
      'toast_task_completed': 'Task completed!',
      'toast_done': 'Done',

      // Delivery notification titles/labels
      'notif_task_accepted': 'Task Accepted',
      'notif_task_rejected': 'Task Rejected',
      'notif_pickup_started': 'Pickup Started',
      'notif_delivery_started': 'Delivery Started',
      'notif_task_completed': 'Task Completed ✓',
      'notif_oiltrade': 'OilTrade',
      'notif_collection_label': 'Collection',
      'notif_purchase_label': 'Purchase',
      'notif_accepted_suffix': 'accepted.',

      // Error messages
      'failed_to_update_availability': 'Failed to update availability',
      'failed_to_submit_ticket': 'Failed to submit ticket.',
      'failed_to_load_products': 'Failed to load products',
    },

    'ar': {
      // General
      'app_name': 'أويل ترايد',
      'ok': 'حسناً',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'close': 'إغلاق',
      'loading': 'جاري التحميل...',
      'error': 'خطأ',
      'success': 'نجح',
      'sign_out': 'تسجيل الخروج',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'confirm': 'تأكيد',
      'yes': 'نعم',
      'no': 'لا',
      'retry': 'إعادة المحاولة',
      'submit': 'إرسال',
      'back': 'رجوع',

      // Auth
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'phone': 'الهاتف',
      'name': 'الاسم الكامل',
      'wilaya': 'الولاية',
      'role': 'الدور',
      'seller': 'بائع',
      'buyer': 'مشتري',
      'delivery': 'عامل التوصيل',
      'create_account': 'إنشاء حساب',
      'select_role': 'اختر دورك',
      'seller_type': 'نوع البائع',
      'house': 'منزلي',
      'house_desc': 'مستخدم فردي',
      'business': 'تجاري',
      'business_desc': 'مطعم أو فندق أو مقهى...',
      'strength_weak': 'ضعيفة',
      'strength_fair': 'مقبولة',
      'strength_good': 'جيدة',
      'strength_strong': 'قوية',
      'sign_in_subtitle': 'سجّل دخولك إلى حسابك',
      'forgot_password': 'نسيت كلمة المرور؟',
      'no_account': 'ليس لديك حساب؟ ',
      'email_not_verified': 'البريد الإلكتروني غير مفعّل',
      'resend_otp_dialog': 'بريدك الإلكتروني غير مفعّل. سنرسل رمز التحقق إلى بريدك.',
      'send_otp': 'إرسال الرمز',
      'verify_email': 'تحقق من البريد',
      'check_email': 'تحقق من بريدك الإلكتروني',
      'otp_sent_to': 'لقد أرسلنا رمزاً مكوناً من 6 أرقام إلى',
      'verify': 'تحقق',
      'resend_in': 'إعادة الإرسال خلال',
      'resend_otp': 'إعادة إرسال الرمز',
      'enter_all_digits': 'الرجاء إدخال جميع الأرقام الستة',
      'invalid_otp': 'الرمز غير صحيح أو منتهي الصلاحية',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رمزاً لإعادة تعيين كلمة المرور.',
      'send_reset_code': 'إرسال رمز الاستعادة',
      'enter_reset_code': 'أدخل رمز الاستعادة',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'set_new_password': 'تعيين كلمة مرور جديدة',
      'code_verified_subtitle': 'تم التحقق من الرمز. اختر كلمة مرور قوية\nlا تقل عن 8 أحرف.',
      'password_mismatch': 'كلمتا المرور غير متطابقتين',
      'password_min': 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
      'resend_code': 'إعادة إرسال الرمز',
      'verify_code': 'التحقق من الرمز',
      'code_resent': 'تم إعادة إرسال الرمز. تحقق من بريدك.',
      'otp_resent': 'تم إعادة إرسال الرمز بنجاح. تحقق من بريدك.',
      'password_reset_success': 'تمت إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.',

      // Profile
      'profile': 'الملف الشخصي',
      'edit_profile': 'تعديل الملف',
      'save_changes': 'حفظ التغييرات',
      'contact_info': 'معلومات الاتصال',
      'activity_stats': 'إحصائيات النشاط',
      'notifications': 'الإشعارات',
      'order_updates_enabled': 'تحديثات الطلبات مفعّلة',
      'notifications_off': 'الإشعارات معطّلة',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'choose_language': 'اختر اللغة',
      'privacy_security': 'الخصوصية والأمان',
      'help_support': 'المساعدة والدعم',
      'share_app': 'مشاركة التطبيق',
      'about': 'عن أويل ترايد',
      'report_problem': 'الإبلاغ عن مشكلة 🚨',
      'report_subtitle': 'افتح تذكرة دعم وسيرد فريقنا في غضون ساعات',
      'availability': 'التوفر',
      'accepting_orders': 'يقبل الطلبات',
      'not_accepting_orders': 'لا يقبل الطلبات',
      'capacity': 'السعة',
      'ccp': 'رقم CCP',
      'not_set': 'غير محدد',
      'collections': 'التجميعات',
      'orders': 'الطلبات',
      'rating': 'التقييم',
      'completed': 'مكتمل',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
      'update_failed': 'فشل التحديث',
      'sign_out_confirm': 'تسجيل الخروج؟',
      'sign_out_confirm_body': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'phone_number': 'رقم الهاتف',
      'max_capacity': 'السعة القصوى (لتر/رحلة)',
      'min_3_chars': 'الحد الأدنى 3 أحرف',
      'valid_phone': 'أدخل رقم هاتف صحيح',
      'required': 'مطلوب',
      'valid_number': 'أدخل رقماً صحيحاً ≥ 1',

      // Help items
      'help_q1': 'كيف يعمل التطبيق؟',
      'help_a1': 'يجمع أويل ترايد ثلاثة أطراف: البائع (يجمع الزيت المستعمل)، والمشتري (يشتريه)، وعامل التوصيل الذي ينقله. لكل دور واجهة مخصصة.',
      'help_q2': 'كيف أطلب تجميع زيتي المستعمل؟',
      'help_a2': 'من الشاشة الرئيسية، اضغط "طلب تجميع"، أدخل الكمية والعنوان وتاريخ الاستلام، ثم أرسل الطلب. سيتم تعيين عامل توصيل تلقائياً.',
      'help_q3': 'كيف أشتري زيتاً كمشترٍ؟',
      'help_a3': 'أنشئ طلب شراء مع تحديد الكمية وعنوان التسليم والتاريخ. يتم احتساب السعر تلقائياً.',
      'help_q4': 'من يتم تقييمه في التطبيق؟',
      'help_a4': 'يتم تقييم عامل التوصيل فقط — من قِبل البائع بعد التجميع ومن قِبل المشتري بعد التسليم. التقييمات من 1 إلى 5 نجوم.',
      'help_q5': 'ما طريقة الدفع المقبولة؟',
      'help_a5': 'يتم الدفع عبر التحويل البريدي (CCP) أو BaridiMob. بعد التحويل، ارفع صورة الإيصال في التطبيق.',
      'help_q6': 'ماذا أفعل إذا واجهت مشكلة؟',
      'help_a6': 'انتقل إلى ملفك الشخصي واضغط "الإبلاغ عن مشكلة" لفتح تذكرة دعم.',
      'common_questions': 'أسئلة شائعة حول استخدام التطبيق',

      // About
      'about_tagline': 'أول منصة جزائرية لتجارة زيت الطهي المستعمل.',
      'copyright': '© 2026 أويل ترايد . جميع الحقوق محفوظة.',
      'version': 'الإصدار 1.0.0',
      'algeria': 'الجزائر',

      // Home - Seller
      'hello': 'مرحباً',
      'request_collection': 'طلب تجميع',
      'request_collection_subtitle': 'جدوِل استلام زيتك المستعمل',
      'collection_history': 'سجل التجميع',
      'recent_collections': 'التجميعات الأخيرة',
      'recent_orders': 'الطلبات الأخيرة',
      'no_orders_yet': 'لا توجد طلبات بعد',
      'no_collections_yet': 'لا توجد تجميعات بعد',
      'view_all': 'عرض الكل',
      'total_earned': 'إجمالي الأرباح',
      'total_sold': 'إجمالي المبيعات',
      'home': 'الرئيسية',
      'history': 'السجل',
      'products': 'المنتجات',
      'status': 'الحالة',
      'liters': 'لتر',
      'liter_unit': 'ل',
      'order_hash': 'طلب #',
      'collection_hash': 'تجميع #',
      'purchase_hash': 'شراء #',
      'quota': 'الحصة',
      'l_per_month': 'ل/شهر',
      'l_per_trip': 'ل / رحلة',

      // Home - Buyer
      'place_order': 'تقديم طلب',
      'place_an_order': 'تقديم طلب',
      'place_order_subtitle': 'اطلب زيت الطهي، يُسلَّم إليك',
      'my_orders': 'طلباتي',
      'subscription': 'الاشتراك',
      'subscription_pending': 'الاشتراك قيد الانتظار',
      'subscription_pending_subtitle': 'الخطة في انتظار موافقة المسؤول',
      'subscribe_to_plan': 'اشترك في خطة',
      'subscribe_to_plan_subtitle': 'اختر Basic أو Premium أو VIP للبدء',
      'upgrade_plan': 'ترقية الخطة ←',
      'active': 'نشط',
      'pending': 'قيد الانتظار',
      'no_active_subscription': 'لا يوجد اشتراك نشط',
      'subscribe': 'اشتراك',

      // Order statuses
      'pending_admin': 'في انتظار الموافقة',
      'assigned': 'تم التعيين',
      'accepted': 'مقبول',
      'in_transit': 'في الطريق',
      'rejected': 'مرفوض',
      'completed_status': 'مكتمل',
      'waitlist': 'قائمة الانتظار',
      'expired': 'منتهية الصلاحية',
      'delivery_rejected': 'مرفوض من السائق',

      // Collection request
      'new_collection': 'طلب تجميع جديد',
      'quantity_liters': 'الكمية (لتر)',
      'pickup_address': 'عنوان الاستلام',
      'pickup_date': 'تاريخ الاستلام',
      'pickup_time': 'وقت الاستلام (اختياري)',
      'notes': 'ملاحظات (اختيارية)',
      'quality': 'الجودة',
      'good_quality': 'جودة جيدة',
      'medium': 'متوسط',
      'submit_request': 'إرسال الطلب',
      'select_date': 'اختر التاريخ',
      'select_time': 'اختر الوقت',
      'estimated_earnings': 'الأرباح المتوقعة',

      // FAQ screen
      'faq_title': 'الأسئلة الشائعة',
      'faq_header': 'كل ما تحتاج معرفته عن الزيت المستعمل',
      'faq_tap_to_read': 'اضغط على أي سؤال لقراءة الإجابة',
      'faq_q1': 'ما هو أويل ترايد؟',
      'faq_a1': 'أويل ترايد هي أول منصة جزائرية مخصصة لتجارة زيت الطهي المستعمل، تعمل كوسيط بين جامعي الزيت المستعمل والمشترين وعمال التوصيل.',
      'faq_q2': 'لماذا لا يجب صب الزيت المستعمل في المصرف؟',
      'faq_a2': 'يمكن للتر واحد من زيت الطهي المستعمل أن يلوث مليون لتر من المياه الجوفية. يسبب صبّه في المصارف انسداد الأنابيب وتضرر شبكات الصرف الصحي والإضرار بالحياة المائية. أويل ترايد يمنحك البديل المسؤول: بيع زيتك بدلاً من إهداره.',
      'faq_q3': 'ما أنواع الزيت المقبولة على المنصة؟',
      'faq_a3': 'نقبل جميع زيوت الطهي المنزلية والتجارية المستعملة، بما فيها:\n\n• زيت عباد الشمس\n\nالشرط الوحيد: أن يكون الزيت خالياً من البقايا الغذائية المفرطة. لا نقبل زيوت المحركات أو المشتقات النفطية.',
      'faq_q4': 'ما الكمية الدنيا لطلب التجميع؟',
      'faq_a4': 'الحد الأدنى لكل طلب خمسة عشر لتراً (15 لتر). لا يوجد حد أقصى — كلما جمعت أكثر، كلما ربحت أكثر.',
      'faq_q5': 'كيف يتم احتساب سعر جمع الزيت؟',
      'faq_a5': 'سعر جمع الزيت المستعمل ثابت. بمجرد تراكم 15 لتراً، تحصل على مكافأة.\n\nيوضح متتبع التقدم داخل التطبيق عدد اللترات التي جمعتها ومتى ستصل إلى الحد الأدنى للدفع.',
      'faq_q6': 'كيف تسير عملية التجميع؟',
      'faq_a6': '١. قدّم طلب تجميع في التطبيق مع تحديد الكمية والعنوان وتاريخ الاستلام.\n٢. يتم تعيين عامل توصيل من ولايتك تلقائياً.\n٣. يصل العامل في الوقت المحدد لاستلام الزيت.\n٤. يتم تحديث رصيد لتراتك فور اكتمال الاستلام.\n٥. يمكنك تقييم عامل التوصيل بعد الاستلام.',
      'faq_q7': 'كيف أحفظ الزيت المستعمل قبل التجميع؟',
      'faq_a7': 'اتبع هذه الإرشادات البسيطة:\n\n• دعه يبرد تماماً قبل التخزين\n• صفّه من بقايا الطعام الكبيرة\n• صبّه في إناء محكم الإغلاق (بلاستيك أو زجاج)\n• خزّنه في مكان بارد بعيداً عن أشعة الشمس المباشرة\n• تجنب خلطه بالماء أو الزيوت الأخرى قدر الإمكان',
      'faq_q8': 'ما خطط الاشتراك المتاحة للمشترين؟',
      'faq_a8': 'يمكن للمشترين الاختيار من بين ثلاث خطط:\n\n• Basic: 100 لتر/شهر — 10,000 دج (أولوية 1)\n• Premium: 200 لتر/شهر — 20,000 دج (أولوية 2)\n• VIP: 300 لتر/شهر — 30,000 دج (أولوية 3)\n\nتحظى الخطط ذات الأولوية الأعلى بالأفضلية في جدولة التوصيل.',
      'faq_q9': 'كيف يعمل نظام التقييم؟',
      'faq_a9': 'بعد كل عملية تجميع أو توصيل، يتم تقييم عامل التوصيل من قِبل البائع أو المشتري بشكل مستقل. تساعد التقييمات على تحسين جودة الخدمة وتحديد أفضل عمال التوصيل.',
      'faq_q10': 'ما الأثر البيئي لاستخدام أويل ترايد؟',
      'faq_a10': 'من خلال تداول الزيت المستعمل بدلاً من إهداره:\n\n• تحمي المياه الجوفية والأنهار من التلوث\n• تقلل انبعاثات الكربون مقارنةً بالحرق\n• تدعم الاقتصاد الدائري\n• تسهم في أهداف الجزائر للتنمية المستدامة\n\nكل لتر تبيعه هو خطوة نحو جزائر أنظف.',

      // Request collection
      'oil_quantity': 'كمية الزيت',
      'oil_photo': 'صورة الزيت',
      'upload_oil_photo': 'رفع صورة الزيت (اختياري)',
      'listing_submitted': 'تم إرسال الطلب!',
      'listing_submitted_body': 'تم إرسال طلبك إلى الإدارة للمراجعة.\nستُخطَر بمجرد الموافقة عليه.',
      'status_pending_admin': 'الحالة: في انتظار موافقة المسؤول',
      'back_to_home': 'العودة للرئيسية',
      'submit_listing': 'إرسال الطلب',
      'submitting': 'جاري الإرسال...',
      'take_photo': 'التقاط صورة',
      'choose_from_gallery': 'اختر من المعرض',
      'use_current_location': 'استخدام الموقع الحالي',
      'getting_location': 'جاري الحصول على الموقع...',

      // Subscription screen
      'choose_a_plan': 'اختر خطة',
      'subscription_submitted': 'تم إرسال الاشتراك!',
      'subscription_submitted_body': 'إيصال دفعتك قيد المراجعة. سيتم تفعيل خطتك بمجرد التأكيد.',
      'payment_ccp_title': 'الدفع عبر CCP / BaridiMob',
      'payment_ccp_body': 'حوّل رسوم الاشتراك إلى حسابنا CCP، ثم ارفع إيصال BaridiMob أدناه.',
      'upload_baridimob_receipt': 'رفع إيصال BaridiMob',
      'tap_to_select_gallery': 'اضغط للاختيار من المعرض',
      'subscribe_now': 'اشترك الآن',
      'priority_score': 'نقاط الأولوية: ',
      'per_month': '/شهر',

      // Place order screen
      'place_oil_order': 'طلب زيت',
      'payment': 'الدفع',
      'added_to_waitlist': 'تمت الإضافة لقائمة الانتظار',
      'order_submitted': 'تم إرسال الطلب!',
      'waitlist_body': 'طلبك في قائمة الانتظار. سيتم معالجته فور توفر المخزون الكافي.',
      'order_submitted_body': 'تم إرسال إيصال دفعتك. سيتحقق المسؤول منه ويعيّن عامل توصيل.',
      'status_waitlisted': 'الحالة: في قائمة الانتظار',
      'status_pending_verification': 'الحالة: في انتظار التحقق',
      'pay_via_baridi': 'الدفع عبر Baridi Mob / CCP',
      'pay_transfer_instruction': 'حوّل المبلغ الدقيق إلى حسابنا CCP أدناه، ثم ارفع إيصال Baridi Mob.',
      'oiltrade_ccp_account': 'حساب CCP لأويل ترايد',
      'upload_payment_receipt': 'رفع إيصال الدفع',
      'tap_to_upload_receipt': 'اضغط لرفع الإيصال (مطلوب)',
      'receipt_note': 'يرجى إرفاق لقطة شاشة أو صورة لتأكيد دفع Baridi Mob.',
      'ive_paid_submit': 'لقد دفعت — إرسال الطلب',
      'back_to_order_details': '← العودة لتفاصيل الطلب',
      'order_form_banner': 'أدخل تفاصيل طلبك. إذا كان المخزون متوفراً، ستُطلب منك الدفع قبل التأكيد.',
      'required_quantity': 'الكمية المطلوبة',
      'oil_quality': 'جودة الزيت',
      'delivery_date': 'تاريخ التوصيل',
      'delivery_location': 'موقع التوصيل',
      'place_order_btn': 'تقديم الطلب',
      'estimated_total': 'الإجمالي التقديري',
      'amount_to_pay': 'المبلغ المستحق',

      // Complaint
      'complaint_title': 'الإبلاغ عن مشكلة',
      'problem_type': 'نوع المشكلة',
      'description': 'الوصف',
      'send': 'إرسال',
      'complaint_screen_title': 'الإبلاغ عن مشكلة 🚨',
      'complaint_support_title': 'افتح تذكرة دعم مباشرة',
      'complaint_support_body': 'سيرد فريقنا في غضون ساعات مباشرةً على بريدك الإلكتروني.',
      'complaint_type_label': 'نوع المشكلة',
      'complaint_desc_label': 'الوصف',
      'complaint_desc_hint': 'اصف المشكلة بالتفصيل...',
      'complaint_submit': 'إرسال التذكرة',
      'complaint_submitted': '✅ تم إرسال التذكرة!',
      'complaint_submitted_body': 'سيرد فريق الدعم خلال 24 ساعة على بريدك الإلكتروني المسجل.',
      'complaint_new_ticket': 'فتح تذكرة جديدة',
      'complaint_go_back': 'العودة',
      'complaint_select_type': 'يرجى اختيار نوع المشكلة',
      'complaint_enter_desc': 'يرجى وصف المشكلة',
      'complaint_type_1': 'لم يُستلم الطلب',
      'complaint_type_2': 'مشكلة في جودة الزيت',
      'complaint_type_3': 'مشكلة مع السائق',
      'complaint_type_4': 'مشكلة في الدفع',
      'complaint_type_5': 'أخرى',

      // Collection history screen
      'first_pickup_hint': 'اطلب أول عملية استلام من قسم الرئيسية',
      'rate_delivery_agent': 'قيّم عامل التوصيل',
      'collection_service_question': 'كيف كانت خدمة التجميع؟',
      'you_rated': 'تقييمك: ',
      'payment_received': 'تم استلام الدفعة',
      'receipt_load_error': 'تعذر تحميل الإيصال',
      'tap_full_size': 'اضغط لعرض بالحجم الكامل',

      // Purchase orders screen
      'order_not_fulfilled_title': 'تعذر تنفيذ الطلب',
      'order_not_fulfilled_body': 'تم إلغاء طلبك لعدم توفر الزيت المطلوب بحلول تاريخ التوصيل.\n\nيرجى تقديم طلب جديد.',
      'dismiss': 'تجاهل',
      'reorder': 'إعادة الطلب',
      'delivery_service_question': 'كيف كانت خدمة التوصيل؟',
      'order_cancelled_status': 'تم إلغاء الطلب — المخزون غير متاح',
      'order_waitlist_status': 'في قائمة الانتظار — انتظار المخزون',
      'order_cancelled_body': 'لم يكن مخزون الزيت متاحاً بحلول تاريخ التوصيل. يرجى تقديم طلب جديد.',
      'order_waitlist_body': 'طلبك في قائمة الانتظار وسيتم تنفيذه عند توفر المخزون.',
      'deliver_prefix': 'تسليم: ',
      'ordered': 'مطلوب',
      'place_order_label': 'تقديم طلب',

      // Delivery home screen
      'payments': 'المدفوعات',
      'avg_rating': 'متوسط التقييم',
      'no_collection_tasks': 'لا توجد مهام تجميع معيّنة',
      'no_purchase_tasks': 'لا توجد مهام شراء معيّنة',
      'status_new': 'جديد',
      'accept_task': 'قبول المهمة',
      'purchases_tab': 'المشتريات',
      'agent_badge': 'عامل',

      // Delivery payments screen
      'my_payments': 'مدفوعاتي',
      'total_received_prefix': 'إجمالي المستلم: ',
      'no_payments_yet': 'لا توجد مدفوعات بعد',
      'paid_on_prefix': 'مدفوع في ',
      'payment_receipt_label': 'إيصال الدفع',
      'receipt_unavailable': 'الإيصال غير متاح',
      'receipt': 'الإيصال',
      'failed_to_load_image': 'تعذر تحميل الصورة',

      // Delivery order detail screen
      'reject_task': 'رفض المهمة',
      'reject_task_confirm': 'هل أنت متأكد أنك تريد رفض هذه المهمة؟ سيتم إعادة تعيينها.',
      'reject': 'رفض',
      'confirm_delivery': 'تأكيد التسليم',
      'confirm_delivery_body': 'تأكيد اكتمال عملية التوصيل.',
      'started_pickup': 'بدء الاستلام',
      'started_delivery': 'بدء التوصيل',
      'delivery_completed': 'تم التوصيل',
      'task_completed': 'تمت المهمة',
      'pickup_location': 'موقع الاستلام',
      'central_depot_pickup': 'المستودع المركزي (نقطة الاستلام)',
      'central_depot_dropoff': 'المستودع المركزي (نقطة الإنزال)',
      'information': 'معلومات',
      'schedule_details': 'الجدول والتفاصيل',
      'date_label': 'التاريخ',
      'time_label': 'الوقت',
      'volume_label': 'الحجم',
      'total_label': 'الإجمالي',
      'notes_label': 'الملاحظات',
      'map': 'الخريطة',
      'collection_task': 'مهمة التجميع',
      'purchase_task': 'مهمة الشراء',
      'not_specified': 'غير محدد',

      // Onboarding screen
      'onboarding_skip': 'تخطي',
      'onboarding_next': 'التالي',
      'onboarding_get_started': 'ابدأ الآن',
      'onboarding_slide1_title': 'مرحباً بك في أويل ترايد',
      'onboarding_slide1_subtitle': 'منصة الزيت المستعمل',
      'onboarding_slide1_desc': 'أول منصة جزائرية تعمل كوسيط بين جامعي زيت الطهي المستعمل والمشترين وعمال التوصيل — كل ذلك في تطبيق واحد.',
      'onboarding_slide2_title': 'بيع زيتك بسهولة',
      'onboarding_slide2_subtitle': 'للبائعين',
      'onboarding_slide2_desc': 'سجّل كمية زيتك المستعمل، حدد تاريخ الاستلام، وانتظر وصول عامل التوصيل.',
      'onboarding_slide3_title': 'اشتر بثقة',
      'onboarding_slide3_subtitle': 'للمشترين',
      'onboarding_slide3_desc': 'اشترك في خطة، قدّم طلبك، واستقبل الزيت الجيد مباشرةً على بابك.',

      // Oil progress widget
      'collection_progress': 'تقدم التجميع',
      'cycle_description': 'تجمع الزيت في دورات من 15 لتر. بمجرد الوصول إلى 15 لتر، يعالج المسؤول تجميعك وتعيد الدورة من الصفر.',
      'cycle_progress': 'تقدم الدورة',
      'to_complete': 'للإكمال',
      'l_left': ' لتر متبقية',
      'cycle_complete_banner': 'اكتملت الدورة! سيعالج المسؤول تجميعك وسيعيد ضبط الدورة.',
      'collect_more_prefix': 'اجمع ',
      'collect_more_suffix': ' لتر أخرى لإكمال هذه الدورة.',

      // Organic products screen
      'organic_products': 'المنتجات العضوية 🌿',
      'certified_products': '🌱 منتجات معتمدة — متاحة للجميع',
      'products_tap_hint': 'اضغط على منتج لعرض التفاصيل والتواصل مع المالك',
      'no_products': 'لا توجد منتجات متاحة',
      'list_product_cta': 'هل تريد إدراج منتجك؟',
      'list_product_body': 'تواصل معنا لإضافة منتجك على أويل ترايد والوصول لآلاف العملاء.',
      'product_description': 'الوصف',
      'owner_info': '📋 معلومات المالك',
      'contact_owner_hint': '💡 تواصل مع المالك مباشرةً للاستفسارات أو الطلبات',

      // Subscription screen
      'plan_liters_month': '{liters} لتر/شهر',
      'val_upload_receipt': 'يرجى رفع إيصال دفع Baridimob',
      'subscription_failed': 'فشل الاشتراك',
      'ccp_account_label': 'رقم حساب CCP:',
      'account_name_label': 'الاسم:',
      'plan_feature_basic_1': 'حصة 100 لتر/شهر',
      'plan_feature_basic_2': 'أولوية توصيل عادية',
      'plan_feature_basic_3': 'دعم عبر البريد الإلكتروني',
      'plan_feature_premium_1': 'حصة 200 لتر/شهر',
      'plan_feature_premium_2': 'أولوية توصيل عالية',
      'plan_feature_premium_3': 'دعم ذو أولوية',
      'plan_feature_vip_1': 'حصة 300 لتر/شهر',
      'plan_feature_vip_2': 'أعلى أولوية توصيل',
      'plan_feature_vip_3': 'دعم مخصص 24/7',

      // Notifications
      'collection_approved_title': 'تمت الموافقة على طلب التجميع',
      'purchase_approved_title': 'تمت الموافقة على طلب الشراء',
      'collection_approved_body': 'تمت الموافقة على طلب تجميعك بكمية {liters} لتر وسيتم تعيين عامل توصيل.',
      'purchase_approved_body': 'تمت الموافقة على طلب شرائك بكمية {liters} لتر وتم تعيين عامل توصيل.',
      'collection_accepted_title': 'عامل التوصيل في الطريق',
      'collection_accepted_body': 'قَبِل عامل التوصيل طلب تجميعك بكمية {liters} لتر.',
      'purchase_accepted_title': 'قَبِل عامل التوصيل طلبك',
      'purchase_accepted_body': 'قَبِل عامل التوصيل طلب شرائك بكمية {liters} لتر.',
      'collection_rejected_title': 'تم رفض طلب التجميع',
      'collection_rejected_body': 'تم رفض طلب تجميعك بكمية {liters} لتر من قِبل الإدارة. اضغط إعادة الطلب للمحاولة مجدداً.',
      'purchase_rejected_title': 'تم رفض طلب الشراء',
      'purchase_rejected_body': 'تم رفض طلب شرائك بكمية {liters} لتر. اضغط إعادة الطلب للمحاولة مجدداً.',
      'notif_action_reorder': 'إعادة الطلب',

      // Validators & hints (register screen)
      'val_name_min': 'يجب أن يكون الاسم 3 أحرف على الأقل',
      'val_email': 'أدخل بريداً إلكترونياً صحيحاً',
      'val_password_required': 'أدخل كلمة المرور',
      'val_ccp_required': 'رقم حساب CCP مطلوب',
      'val_capacity_required': 'أدخل سعة مركبتك',
      'val_capacity_min': 'أدخل سعة صحيحة (الحد الأدنى 1 لتر)',
      'hint_phone': '05XXXXXXXX',
      'hint_ccp': '0000000000/00',
      'hint_capacity': 'مثال: 20',
      'label_ccp_baridi': 'رقم حساب CCP / Baridi Mob',
      'label_vehicle_capacity': 'سعة المركبة (لتر)',

      // Auth errors
      'unknown_role': 'دور غير معروف. يرجى التواصل مع الدعم.',
      'something_went_wrong': 'حدث خطأ ما.',
      'password_reset_manual': 'تمت إعادة تعيين كلمة المرور. يرجى تسجيل الدخول يدوياً.',
      'failed_to_reset_password': 'فشل إعادة تعيين كلمة المرور',
      'failed_to_resend_otp': 'فشل إعادة إرسال الرمز',

      // Request collection validators & info
      'label_quantity_min5': 'الكمية (لتر) — الحد الأدنى 5 لتر',
      'val_enter_quantity': 'أدخل الكمية',
      'val_min_5_liters': 'الحد الأدنى 5 لتر',
      'val_select_pickup_date': 'يرجى اختيار تاريخ الاستلام',
      'val_select_pickup_location': 'يرجى اختيار موقع الاستلام',
      'failed_to_submit': 'فشل إرسال الطلب',
      'label_address': 'العنوان',
      'val_enter_address': 'أدخل عنوان الاستلام',
      'orders_under_15l_info': 'الطلبات التي تقل عن 15 لتر تُجمع في نقاط استلام مشتركة — مرتين في الأسبوع.',
      'no_pickup_locations': 'لا توجد نقاط استلام متاحة في منطقتك. تواصل مع الدعم.',
      'listing_review_info': 'سيتم مراجعة طلبك من قِبل الإدارة قبل تعيين عامل توصيل.',

      // Place order validators & snacks
      'location_disabled': 'خدمة الموقع معطّلة',
      'location_permission_denied': 'لم تُمنح إذن الموقع',
      'location_error_prefix': 'تعذر الحصول على الموقع: ',
      'val_select_delivery_date': 'يرجى اختيار تاريخ التوصيل',
      'val_quantity_valid': 'أدخل كمية صحيحة',
      'val_min_20l': 'الحد الأدنى للطلب هو 20 لتر',

      // Payment screen
      'order_confirmed': 'تم تأكيد الطلب!',
      'order_placed_prefix': 'الطلب #',
      'order_placed_suffix': ' تم تقديمه بنجاح.',
      'order_details': 'تفاصيل الطلب',
      'order_id': 'رقم الطلب',
      'quantity': 'الكمية',
      'total_amount': 'المبلغ الإجمالي',
      'address_label': 'العنوان',
      'payment_instructions': 'تعليمات الدفع',
      'payment_instructions_body': 'حوّل المبلغ الإجمالي باستخدام إحدى الطرق أدناه، ثم أظهر دليل الدفع لعامل التوصيل.',
      'ccp_cheque_postal': 'CCP (شيك بريدي)',
      'baridimob': 'BaridiMob',
      'done_go_to_orders': 'تم — الذهاب لطلباتي',
      'copied_to_clipboard': 'تم النسخ إلى الحافظة',

      // Delivery action toasts
      'toast_task_accepted': 'تم قبول المهمة!',
      'failed_to_accept_task': 'فشل قبول المهمة',
      'toast_task_rejected': 'تم رفض المهمة.',
      'toast_pickup_started': 'بدأ الاستلام!',
      'toast_delivery_started': 'بدأ التوصيل!',
      'toast_task_completed': 'اكتملت المهمة!',
      'toast_done': 'تم',

      // Delivery notification titles/labels
      'notif_task_accepted': 'تم قبول المهمة',
      'notif_task_rejected': 'تم رفض المهمة',
      'notif_pickup_started': 'بدأ الاستلام',
      'notif_delivery_started': 'بدأ التوصيل',
      'notif_task_completed': 'اكتملت المهمة ✓',
      'notif_oiltrade': 'أويل ترايد',
      'notif_collection_label': 'تجميع',
      'notif_purchase_label': 'شراء',
      'notif_accepted_suffix': 'مقبول.',

      // Error messages
      'failed_to_update_availability': 'فشل تحديث حالة التوفر',
      'failed_to_submit_ticket': 'فشل إرسال التذكرة.',
      'failed_to_load_products': 'فشل تحميل المنتجات',
    },
  };
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(_) => false;
}
